name: build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out code
        uses: actions/checkout@v4
      - name: setup Go 1.21
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: build
        run: go build
      - name: install dependency
        run: if [ $(uname) == "Darwin" ]; then brew install gnu-sed ;fi
